name: py38
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.*
  - pip>=23.0.0
  - setuptools>=59.5.0
  - cuda=11.7.*
  - cuda-compiler=11.7.*
  - cuda-cudart=11.7.*
  - cuda-nvcc=11.7.*
  - cuda-runtime=11.7.*
  - cudatoolkit=11.7.*
  - pip:
      - -r requirements.txt
