_target_: src.model.GNeVALightningModule
_convert_: "all"

network_kwargs:
  map_in_features: ???
  map_hidden_size: 64
  map_out_size: 128
  map_num_layers: 3
  motion_in_features: ???
  motion_hidden_size: 128
  motion_out_size: 128
  motion_num_layers: 3
  num_encoder_heads: 8
  intention_hidden_size: 128
  predict_actions: true
  observation_horizon: ???
  prediction_horizon: ???
  dropout: 0.1
  num_goal_heads: 6
  num_modals: 6
  grid_size: 0.5
  iou_radius: 1.0
  iou_threshold: 0.0
  alpha: 10.0
