name: Code Quality Master

on:
  push:
    branches: [master]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Pythona 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run pre-commits
        uses: pre-commit/action@v2.0.3
